Fix failing tests due to tty-screen update
tty-screen is updated to 0.8.0.

```
NoMethodError:
  undefined method `ioctl' for #<StringIO:0x00561e7c808478>
```